project_id = "tkpogjvlepwrsswqzsdu"

[functions.drive-list]
verify_jwt = true

[functions.drive-download]
verify_jwt = true

[functions.gmail-list]
verify_jwt = true

[functions.gmail-download-attachment]
verify_jwt = true

[functions.set-approval]
verify_jwt = true

[functions.risk-check]
verify_jwt = true

[functions.spend-analytics]
verify_jwt = true

[functions.esg-map]
verify_jwt = true

[functions.generate-qr]
verify_jwt = true

[functions.ocr-hf]
enabled = true
verify_jwt = true
import_map = "./functions/ocr-hf/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ocr-hf/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ocr-hf/*.html" ]
