project_id = "tkpogjvlepwrsswqzsdu"

[functions.drive-list]
verify_jwt = true

[functions.drive-download]
verify_jwt = true

[functions.gmail-list]
verify_jwt = true

[functions.gmail-download-attachment]
verify_jwt = true
